version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: pharmacy-postgres
    environment:
      POSTGRES_PASSWORD: pass123
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"

  mongo:
    image: mongo:latest
    container_name: pharmacy-mongodb
    ports:
      - "27017:27017"

  redis:
    image: redis/redis-stack-server:latest
    container_name: pharmacy-redis
    ports:
      - "6379:6379"

  stripe-cli:
    network_mode: host
    image: stripe/stripe-cli
    container_name: stripe-cli